#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=PCWRT - New easy to use Web Interface
LUCI_DEPENDS:=+uhttpd +libuci-lua +luci-base +luci-compat +luci-lib-json +libiwinfo-lua

PKG_BUILD_DEPENDS:=iwinfo
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature


